void main(){
 try{
   print(10~/0);
 }on Exception catch(e){
   print("error");
 }catch(e){
   print("err");
 }
}